#!/bin/bash

IMAGE='microminion/1tp-registrar'

echo "Building docker container to run 1tp registrar service"
cp ./Dockerfile ../Dockerfile
pushd ../. >> /dev/null
docker build -t ${IMAGE} .
popd >> /dev/null
rm ../Dockerfile
echo "Done"
