#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: ./run <configfile>, e.g. ./run default.conf"
  exit 0
fi

IMAGE='microminion/1tp-registrar'
CMD='node index.js -c config/'$1

docker run -d --name=1tp-registrar --net=host $IMAGE $CMD
